### ISSUE TITLE
添加对 Rye 的支持

### ISSUE THREAD

**Issue by kenvix** [RubyMetric/chsrc#127]
### 描述新的换源目标

Rye 是一款较新的 **Python** **包管理器**，旨在解决 Pip 和 Conda 效率低、冗余大的问题。
官方的地址是：https://rye.astral.sh/

### 请尽可能提供可参考的换源方法

使用 rye config --show-path 命令取得配置文件路径。用文本编辑器打开配置文件，并添加如下内容：

```toml
[[sources]]
name = "default"
url = "https://mirrors.aliyun.com/pypi/simple/"
```

### 请尽可能提供已有镜像站

与pypi共享相同的镜像站
