### ISSUE TITLE
Rust 镜像站 RsProxy.cn

### ISSUE THREAD

**Issue by ccmywish** [RubyMetric/chsrc#68]
@fortystory

此后Rust相关的镜像站讨论可在这里，欢迎你持续关注，若能维护文档就更好了 🤝
1. https://github.com/RubyMetric/chsrc/wiki/Rust-MirrorSite
2. https://github.com/RubyMetric/chsrc/discussions/67

<br>

此次增加站点: https://rsproxy.cn/

换源说明: https://bytedance.larkoffice.com/docs/doccn8vZuDB541t8zTJyTUbZZxc

**Comment by ccmywish** [comment]
@fortystory 我不确认是否是换这个源 URL，请你帮忙确认一下：

https://github.com/RubyMetric/chsrc/commit/34ec28100a1830220cae1b3e7212e7c21ff4dffd#diff-10a3a4cd480d4dc1c8642373e85a43d02b66f1ad428e401560e117890f8a6c91R24

**Comment by fortystory** [comment]
我理解生成的配置大概是:
```toml
[source.crates-io]
replace-with = 'mirror'
[source.mirror]
registry = "sparse+https://rsproxy.cn/index/"
```


这个配置我试了,可以正常执行`cargo build`
